#+title: System setup
#+description: reproducing my system from a clean Ubuntu install
#+startup: show2levels

* Step 1: Rclone
Restore access to all personal files.
** Install rclone
https://rclone.org/
#+begin_src bash
  sudo apt install rclone
#+end_src
** Restore home folder
Assumes home folder is ~/home/ren/~ and backup copy of the home folder is available under ~/media/ren/fullBackup/ren/~
#+begin_src bash
  rclone copy /media/ren/fullBackup/ren/ /home/ren/ --progress
#+end_src
** (later) Set up remote drive
* Step 2: Bitwarden and Firefox
Restore access to all internet resources, which may be locked behind an account.
** Install bitwarden
https://bitwarden.com/
#+begin_src bash
  sudo snap install bitwarden
#+end_src
** Sign in to firefox
Assumes existence of a firefox account, which will then automatically download all official extensions
** Install bypass paywalls clean
Disables paywall for most mainstream websites
https://gitflic.ru/project/magnolia1234/bypass-paywalls-firefox-clean
** In ~about:config~ set ~browser.download.start_downloads_in_tmp_dir~ to true
Download pdfs to be opened to [[file:/tmp/]] instead of [[file:Downloads/]].
* Step 3: Gnome
Restore general look of the system
** Appearance
- enable dark mode
- switch accent colour to magenta
- change background
** Terminal
- in "Preferences" -> "Appearance" -> "Palette" select "Dracula"
** Accessability
- disable animations for
  + instant switching between workspaces
  + instant opening and closing of apps
** Sound
- set "Alert Sound" to "None"
** gnome-tweaks
#+begin_src bash
  sudo apt install gnome-tweaks
#+END_SRC
- in "Keyboard" -> "Additional Layout Options" toggle "Caps Lock as Ctrl"
- will allow for adding apps to startup applications
** gnome-shell-extension-manager
#+begin_src bash
  sudo apt install gnome-shell-extension-manager
#+END_SRC
- disable "Desktop Icons"
- in "Ubuntu Dock", toggle "Intelligent autohide" to increase screen real estate
- install "Hide Top Bar" to increase screen real estate
- install "Workspace Matrix" to arrange workspaces as a matrix
- install "Caffeine" to simplify disable suspension temporarily
* Step 4: Emacs (and work related packages)
Restore look and functionality of emacs
** Install emacs and clone configuration
#+begin_src bash
  sudo snap install emacs --classic
  git clone https://github.com/YueRen/.emacs.d.git
#+end_src
** Install ~vterm~
#+begin_src bash
  sudo apt install cmake libtool-bin
#+end_src
~vterm~ will be installed automatically the first time it is run.
** Install ~copilot~
#+begin_src bash
  sudo snap install node --classic # debian package too outdated
  npm install @github/copilot-language-server
#+end_src
Run ~M-x copilot-install-server~.
** In Emacs, install nerd-icons
Run ~M-x nerd-icons-install-fonts~.
** Install ~julia~
#+begin_src bash
  sudo apt install curl
#+end_src
Follow instructions on
https://julialang.org/downloads/
** Install latex
#+begin_src bash
  sudo apt install texlive texlive-science texlive-pictures texlive-latex-extra texlive-fonts-extra texlive-bibtex-extra biber bibtool
#+end_src
The texlive packages are needed for the following packages
- texlive: base install
- texlive-latex-extra: enumitem
- texlive-bibtex-extra: biblatex
- texflive-fonts-extra: listings
- texlive-pictures: for tikz
- texlive-science: algorithm2e
Run ~M-x pdf-tools-install~ to install Emacs pdf-viewer.
* Step 5: Essentials
Installs a variety of software used day-to-day.  Required for [[file:.profile][.profile]] to work as intended.
** apt
#+begin_src bash
  sudo apt install bat fd-find lsd plocate ripgrep zoxide
#+end_src
Restart running terminals, necessary for zoxide to work properly.
*** bat
for `bat`, a better `cat`
see [[file:.profile][.profile]] for alias
*** fd-find
for `fd`, a better `find`
see [[file:.profile][.profile]] for alias
*** lsd
for `lsd`, a better `ls`
see [[file:.profile][.profile]] for alias
*** plocate
for `locate` to find files in system
run ~sudo updatedb~ to update database
*** ripgrep
for `rg`, a better `grep`
*** zoxide
for `z`, a better `cd`
see [[file:.bashrc][.bashrc]] for setup
see [[file:.profile][.profile]] for alias
** snap
#+begin_src bash
  sudo snap install btop cheat chromium gdu gimp libreoffice mpv slack tldr yt-dlp zotero-snap
#+end_src
*** btop
better system monitor
*** cheat
custom cheat sheets
*** chromium
alternative browser
*** gdu-disk-usage-analyzer
better disk usage analyzer
see [[file:.profile][.profile]] for alias
*** gimp
image software
*** libreoffice
office suite
*** mpv
audio / video player
*** slack
*** tldr
better man pages
*** yt-dlp
yt downloader
*** zotero-snap
remember to install better bibtex extension for:
. automatic export to [[file:all.bib][all.bib]]
. parsing articles on [[https://zbmath.org/][zbmath]]
https://retorque.re/zotero-better-bibtex/

Set citation key formula in "Edit" -> "Settings" -> "Better Bibtex" to
#+begin_src
  (authIni(n=1,sep='') > 2 ? authIni(n=1,sep='') : authorsn) + year
#+end_src
- ~authIni(n=1,sep='')~ is the string consisting of the first letter of all authors
- ~authIni(n=1,sep='') > 2~ checks whether there are more than two authors
- ~authorsn~ is the last name of all authors
- ~year~ inserts the year
** flatpak
Install flatpaks and register flathub
#+begin_src bash
  sudo apt install flatpak
  flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
#+end_src
* Step 6: Singular
#+begin_src bash
  sudo apt install libreadline-dev libgmp-dev libcdd-dev
#+end_src
Install Singular from github: https://github.com/Singular/Singular

If unable to find shared object files:
- add line with ~/usr/local/lib~ to [[file:/etc/ld.so.conf.d/usr-local.conf]]
- run ~sudo ldconfig~
* Step 7: Polymake
#+begin_src bash
  sudo apt install polymake binutils-gold graphviz
#+end_src
- ~binutils-gold~ is required for ~visualize_in_surface~
- ~graphviz~ is required for graph visualizations, may be called from OSCAR via
#+begin_src julia
  G = graph_from_edges([[1,2], [1,3], [2,3], [2,4], [3,4], [3,5], [4,5], [4,6], [5,6]])
  visualize(G, backend=:graphviz)
#+end_src
* Extras
** BambuStudio
For 3d printing
#+begin_src
  flatpak install flathub com.bambulab.BambuStudio
#+end_src
** displaylink
https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu
** steam
#+begin_src bash
  sudo snap install steam
#+end_src
** lutris
#+begin_src bash
  flatpak install flathub net.lutris.Lutris
#+end_src
